### ISSUE TITLE
Paper Release

### ISSUE THREAD

**Issue by wenzhengzeng** [Lillianwei-h/MMIE#1]
Thank you for your nice work. It seems that the provided Arxiv URL is not correct. Could you give an approximate date for the release of the full paper? Thank you!

**Comment by Lillianwei-h** [comment]
Thank you very much for your attention to our work! Unfortunately, due to the recent high volume of submissions to arXiv, our paper has been delayed two days longer than expected. We expect it to be published by next Monday, 14 October. And we'll update the link as soon as it's available.

**Comment by wenzhengzeng** [comment]
Thank you!

**Comment by Lillianwei-h** [comment]
Hi, we are saddened to discover that our paper has likely been on hold due to a classification error😭. We are currently in contact with arXiv to request removal and re-upload. Once the paper is successfully published, we will respond to this issue. We sincerely apologize for the delay and thank you for your patience.

**Comment by Lillianwei-h** [comment]
Our paper has been successfully published today. The link is https://arxiv.org/abs/2410.10139. Thank you for waiting!!

**Comment by wenzhengzeng** [comment]
Thank you!
