### ISSUE TITLE
Request for Inference Code

### ISSUE THREAD

**Issue by xyliugo** [Lillianwei-h/MMIE#4]
Hi, thank you for sharing your work and this repository! If possible, could you please release the inference code (raw code is also okay) for the baseline models, especially Emu2? I noticed that you mentioned using a pipeline to combine Emu2-Chat and Emu2-Gen to complete interleaved tasks, and I’m very interested in the detailed implementation. Thanks again! Nice work!

**Comment by Lillianwei-h** [comment]
Hello! Thank you for your interest in our work! The inference code of Emu2 is copied directly from https://huggingface.co/BAAI/Emu2-Chat and https://huggingface.co/BAAI/Emu2-Gen. We use Emu2-Chat to generate text and then use the text as input to let Emu2-Gen generate images. Actually the process is more like integrated models. But since Emu2-Chat and Emu2-Gen are both fine-tuned from Emu2, we have categorized them as interleaved models.
For other models' inference codes, all of them are similarly copied and adapted from their official released versions. And specifically for Gill, since the official code doesn't work well, we release our revised version at https://github.com/Lillianwei-h/runable-gill, but it is not well tested for other environments.

**Comment by xyliugo** [comment]
Thanks! That sounds reasonable. I have a follow-up question: since Emu2-Chat is not fine-tuned on interleaved datasets, how does the model decide when to generate text and when to generate an image? Or is it simply a fixed pipeline, text first (Emu2-Chat) and then image (Emu2-Gen)?

**Comment by Lillianwei-h** [comment]
You are right! It is a fixed pipeline.
