### ISSUE TITLE
Issue with Image Truncation and Score Format in Evaluation

### ISSUE THREAD

**Issue by zry13** [Lillianwei-h/MMIE#5]
Hello, Thank you very much for your work. I encountered the following two issues while trying to run the code and hope to get some help:

1. In the 'get_dataset()' method of 'dataset.py', I noticed that input images beyond a count of three are truncated. In fact, many QAs contain more than three images. Could this have any impact on the final evaluation?

2. When evaluating the first 500 cases in 'data.json' downloaded from Hugging Face, specifically focusing on dialogues of PBL and SA types, I observed that the fine-tuned InternVl2-4B often fails to follow instructions and provide a correctly formatted "##score". Only about one-third of the inputs result in a corresponding score.I wonder if there is anything wrong?

**Comment by Lillianwei-h** [comment]
Hi! Thanks for noticing our work!
Since the fine-tuned InternVL-2 has a maximum token length of 4096, we have to limit the number of images, otherwise MMIE-Score would not work properly. Actually the truncation sessions for question and answer are different. The question part can have a maximum of 4 images (line 60-61 in `dataset.py`). In MMIE, only a small part of questions in the MSR category have more than 1 image (and they don't need any image in the answer) and a really small part have more than 4 images. The impact is so small that could be neglected.
Meanwhile, the image limit of the answer part is 2. It can be set to 3, but for stability, I suggest containing only 2 images in the answer part. I think the second problem is also due to exceeding the token limit. In my own experiment (which follows the image number restriction), the percentage of valid format is about 98%.
We are also preparing to train a new scoring model that can handle longer input. Thanks for your feedback!

**Comment by zry13** [comment]
Thank you for your reply. I attempted to add a restriction on the number of input images, and among about 400 samples, the percentage of valid formats reached 76%. Although it hasn't reached 98%, it's a considerable improvement compared to the previous one-third. Looking forward to your future work.
